#Question 10
#Fibonacci sequence problem

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci(num):
    if num == 0:
        return 0
    elif num == 1:
        return 1
    else:
        sum1 = 0
        L = [0,1]
        for i in range(1,num):
            L.append(L[-1] + L[-2])

        if L[-1] > 4000000:
            return False
        else:
            print(L)
            for i in range(num):
                if (L[i] % 2) == 0:
                    sum1 = L[i] + sum1

        print(100*"-")
        print(sum1)


fibonacci(20)

